import { measureText } from "../src/cli/text.ts";
import { glyphAtlasData } from "../src/glyphs/atlas.ts";
import type { Glyph } from "../src/glyphs/types.ts";
import {
  type GlyphAtlasValidationInput,
  validateGlyphAtlas,
} from "../src/glyphs/validation.ts";

/** Project approved curation without shipping the research or measurement graph. */
export function projectGlyphs(
  data: GlyphAtlasValidationInput,
): readonly Glyph[] {
  validateGlyphAtlas(data);
  const canonical = new Map(
    data.canonical.map((record) => [record.id, record]),
  );
  return data.aliases.filter(({ publication }) => publication === "candidate")
    .map((alias): Glyph => {
      const record = canonical.get(alias.canonicalId)!;
      const terminal = alias.surfaces.terminal;
      return {
        name: alias.name,
        title: alias.discoveryTitle,
        unicode: record.text,
        columns: record.terminalWidth,
        category: alias.category,
        recommendation: alias.recommendation.state,
        browser: alias.surfaces.browser.posture,
        terminal: terminal.posture,
        browserGuidance: alias.surfaces.browser.guidance,
        terminalGuidance: terminal.guidance,
        ...(terminal.posture === "supported"
          ? {
            ascii: {
              text: terminal.asciiFallback.text,
              columns: measureText(terminal.asciiFallback.text),
              fidelity: terminal.asciiFallback.fidelity,
            },
          }
          : {}),
      };
    });
}

/** Generate a literal vocabulary whose types and runtime data share one source. */
export function generateGlyphs(data = glyphAtlasData): string {
  const records = projectGlyphs(data);
  return `/**
 * Generated by deno task codegen from src/glyphs/atlas.ts. Do not edit.
 * @module
 */
import type { Glyph } from "../glyphs/types.ts";

/** Approved curated Glyph definitions, isolated from the private Atlas. */
export const glyphDefinitions = ${
    JSON.stringify(records, null, 2)
  } as const satisfies readonly Glyph[];
`;
}
